# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cedbf22d90988306302ecfdde5db189efc8f4cd71c53e7ce102c7bc9211951143533d4a94c462d1acdb422da9d0a52b0ef8d23961ca27635d7623d657e5def7

test:
  secret_key_base: 343f75ff90c5780647df712c87315985631a9759c1ac9730dcdfe2933b4f03e168968d537bfcb5e753d8031b02d910ed618a8aeaffece5856d360bed1aa0f545

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
